#!/usr/bin/env bash
# dig to domain

domain="$1"
subdomain="$2"

if [ "$#" -eq 0 ]; then
    exit
fi
if [ "$#" -eq 1 ]; then

    subdomains=("www" "lb-01" "web-01" "web-02")
    for s in "${subdomains[@]}"; do
        record=$(dig $s.$domain | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
        ip=$(dig $s.$domain | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
        echo "The subdomain $s is a" $record "record and points to" $ip
    done
    exit
fi
record=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
ip=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
echo "The subdomain" $subdomain "is a" $record "record and points to" $ip
