#!/usr/bin/env bash
#!/usr/bin/env bash
# Bash script configures your Nginx server to have a custom 404 page 
#that contains the string Ceci n'est pas une page.

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=91I8sSLrEok permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i "/server_name _;/a add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart