#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and

i=1
while [ $i -le 10 ]
        do
        
        if [ $i -eq 4 ]; then
                echo "bad luck"
        elif [ $i -eq 8 ]; then
                echo "good look"
        else
                echo "Holberton School"
        fi
        i=$((i += 1))
        done
