#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and

hour=0
while [ $hour -le 12 ]; do
        echo "Hour: "$hour
        min=1
        while [ $min -le 59 ]; do
                echo $min
                min=$((min += 1))
                done
        hour=$((hour += 1))
        done