#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts tmp_hosts
sed -i s/127.0.0.1/127.0.0.2/g tmp_hosts
echo 8.8.8.8 facebook.com >> tmp_hosts
sudo cp tmp_hosts /etc/hosts
