#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill nginx
sudo -u nginx service nginx start
