#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
